version: '3.0'

services:
   db:
     image: mysql:5.7
     container_name: TweetServerDatabase
     environment:
       MYSQL_DATABASE: db
       MYSQL_ROOT_PASSWORD: root
     ports:
       - "8092:8092" 
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

volumes:
    dbdata: